import fonts from './fonts';

export default {
  '900': {
    fontFamily: fonts.display,
    fontSize: '35px',
    fontWeight: 700,
    lineHeight: '40px',
    letterSpacing: '-0.01em',
    marginTop: '52px',
  },
  '800': {
    fontFamily: fonts.display,
    fontSize: '29px',
    fontWeight: 700,
    lineHeight: '32px',
    letterSpacing: '-0.01em',
    marginTop: '40px',
  },
  '700': {
    fontFamily: fonts.display,
    fontSize: '24px',
    fontWeight: 700,
    lineHeight: '28px',
    letterSpacing: '-0.01em',
    marginTop: '40px',
  },
  '600': {
    fontFamily: fonts.display,
    fontSize: '20px',
    fontWeight: 700,
    lineHeight: '24px',
    letterSpacing: '-0.008em',
    marginTop: '28px',
  },
  // Default
  '500': {
    fontFamily: fonts.ui,
    fontSize: '16px',
    fontWeight: 700,
    lineHeight: '20px',
    letterSpacing: '-0.006em',
    marginTop: '24px',
  },
  '400': {
    fontFamily: fonts.ui,
    fontSize: '14px',
    fontWeight: 600,
    lineHeight: '20px',
    letterSpacing: '-0.003em',
    marginTop: '16px',
  },
  '300': {
    fontFamily: fonts.ui,
    fontSize: '12px',
    fontWeight: 600,
    lineHeight: '16px',
    letterSpacing: 0,
    marginTop: '16px',
  },
  '200': {
    fontFamily: fonts.ui,
    fontSize: '11px',
    fontWeight: 600,
    lineHeight: '16px',
    letterSpacing: 0,
    marginTop: '16px',
  },
  '100': {
    fontFamily: fonts.ui,
    fontSize: '11px',
    fontWeight: 600,
    textTransform: 'uppercase',
    lineHeight: '16px',
    letterSpacing: '0.054em',
    marginTop: '16px',
  },
};
